version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: go_book
      POSTGRES_USER: postgres
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
